-- AlterTable
ALTER TABLE `notifications` MODIFY `type` ENUM('BOOKING_CREATED', 'BOOKING_ACCEPTED', 'BOOKING_REJECTED', 'TRIP_STARTED', 'TRIP_COMPLETED', 'TRIP_CANCELLED', 'PAYMENT_RECEIVED', 'PAYMENT_FAILED', 'PAYMENT_REQUEST', 'PAYMENT_REQUESTED', 'DRIVER_ARRIVED', 'SYSTEM_ALERT', 'EMERGENCY_ALERT') NOT NULL;
