import { PrismaClient, UserRole, TruckType, TruckQuality } from '@prisma/client';

const prisma = new PrismaClient();

export async function seedDrivers() {
  console.log('🚚 Seeding drivers...');
  
  const driverUsers = await prisma.user.findMany({
    where: { role: UserRole.DRIVER }
  });

  const locations = [
    { name: 'Dhaka Central, Dhaka', lat: 23.8103, lng: 90.4125 },
    { name: 'Dhaka North, Dhaka', lat: 23.7937, lng: 90.4066 },
    { name: 'Dhaka South, Dhaka', lat: 23.7099, lng: 90.4071 },
    { name: 'Gulshan, Dhaka', lat: 23.7890, lng: 90.4152 },
    { name: 'Banani, Dhaka', lat: 23.7936, lng: 90.4068 },
    { name: 'Dhanmondi, Dhaka', lat: 23.7465, lng: 90.3760 },
    { name: 'Mirpur, Dhaka', lat: 23.8103, lng: 90.3667 },
    { name: 'Uttara, Dhaka', lat: 23.8747, lng: 90.4006 },
    { name: 'Tejgaon, Dhaka', lat: 23.7639, lng: 90.3929 },
    { name: 'Farmgate, Dhaka', lat: 23.7564, lng: 90.3890 },
    { name: 'Mohammadpur, Dhaka', lat: 23.7586, lng: 90.3580 },
    { name: 'Rampura, Dhaka', lat: 23.7631, lng: 90.4255 },
    { name: 'Badda, Dhaka', lat: 23.7787, lng: 90.4266 },
    { name: 'Khilkhet, Dhaka', lat: 23.8284, lng: 90.4259 },
    { name: 'Gabtali, Dhaka', lat: 23.7743, lng: 90.3448 },
    { name: 'Khilgaon, Dhaka', lat: 23.7460, lng: 90.4479 },
    { name: 'Khilkhet, Dhaka', lat: 23.8284, lng: 90.4259 },
  ];

  const drivers = [
    {
      userId: driverUsers[0].id,
      truckType: TruckType.MINI_TRUCK,
      capacity: 1.0,
      quality: TruckQuality.EXCELLENT,
      license: 'DL-123456789',
      registration: 'DHK-123456',
      documents: ['license.pdf', 'registration.pdf', 'insurance.pdf', 'fitness.pdf'],
      location: locations[0].name,
      latitude: locations[0].lat,
      longitude: locations[0].lng,
      isAvailable: true,
      isVerified: true,
      rating: 4.8,
      totalTrips: 45
    },
    {
      userId: driverUsers[1].id,
      truckType: TruckType.PICKUP,
      capacity: 2.0,
      quality: TruckQuality.GOOD,
      license: 'DL-987654321',
      registration: 'DHK-654321',
      documents: ['license.pdf', 'registration.pdf', 'insurance.pdf'],
      location: locations[1].name,
      latitude: locations[1].lat,
      longitude: locations[1].lng,
      isAvailable: true,
      isVerified: true,
      rating: 4.5,
      totalTrips: 32
    },
    {
      userId: driverUsers[2].id,
      truckType: TruckType.LORRY,
      capacity: 5.0,
      quality: TruckQuality.EXCELLENT,
      license: 'DL-456789123',
      registration: 'CTG-789123',
      documents: ['license.pdf', 'registration.pdf', 'insurance.pdf', 'fitness.pdf', 'route-permit.pdf'],
      location: locations[8].name,
      latitude: locations[8].lat,
      longitude: locations[8].lng,
      isAvailable: false,
      isVerified: true,
      rating: 4.9,
      totalTrips: 78
    },
    {
      userId: driverUsers[3].id,
      truckType: TruckType.TRUCK,
      capacity: 8.0,
      quality: TruckQuality.GOOD,
      license: 'DL-789123456',
      registration: 'SYL-456789',
      documents: ['license.pdf', 'registration.pdf'],
      location: locations[10].name,
      latitude: locations[10].lat,
      longitude: locations[10].lng,
      isAvailable: true,
      isVerified: false,
      rating: 4.2,
      totalTrips: 15
    },
    {
      userId: driverUsers[4].id,
      truckType: TruckType.PICKUP,
      capacity: 2.5,
      quality: TruckQuality.AVERAGE,
      license: 'DL-321654987',
      registration: 'DHK-987654',
      documents: ['license.pdf', 'registration.pdf'],
      location: locations[2].name,
      latitude: locations[2].lat,
      longitude: locations[2].lng,
      isAvailable: true,
      isVerified: true,
      rating: 4.0,
      totalTrips: 28
    },
    {
      userId: driverUsers[5].id,
      truckType: TruckType.MINI_TRUCK,
      capacity: 1.5,
      quality: TruckQuality.GOOD,
      license: 'DL-147258369',
      registration: 'DHK-147258',
      documents: ['license.pdf', 'registration.pdf', 'insurance.pdf'],
      location: locations[3].name,
      latitude: locations[3].lat,
      longitude: locations[3].lng,
      isAvailable: true,
      isVerified: true,
      rating: 4.6,
      totalTrips: 52
    },
    {
      userId: driverUsers[6].id,
      truckType: TruckType.LORRY,
      capacity: 4.0,
      quality: TruckQuality.EXCELLENT,
      license: 'DL-963852741',
      registration: 'CTG-963852',
      documents: ['license.pdf', 'registration.pdf', 'insurance.pdf', 'fitness.pdf'],
      location: locations[9].name,
      latitude: locations[9].lat,
      longitude: locations[9].lng,
      isAvailable: true,
      isVerified: true,
      rating: 4.7,
      totalTrips: 65
    },
    {
      userId: driverUsers[7].id,
      truckType: TruckType.TRUCK,
      capacity: 10.0,
      quality: TruckQuality.EXCELLENT,
      license: 'DL-852963741',
      registration: 'RAJ-852963',
      documents: ['license.pdf', 'registration.pdf', 'insurance.pdf', 'fitness.pdf', 'route-permit.pdf'],
      location: locations[11].name,
      latitude: locations[11].lat,
      longitude: locations[11].lng,
      isAvailable: false,
      isVerified: true,
      rating: 4.9,
      totalTrips: 89
    },
    {
      userId: driverUsers[8].id,
      truckType: TruckType.PICKUP,
      capacity: 2.0,
      quality: TruckQuality.AVERAGE,
      license: 'DL-741852963',
      registration: 'KHU-741852',
      documents: ['license.pdf', 'registration.pdf'],
      location: locations[12].name,
      latitude: locations[12].lat,
      longitude: locations[12].lng,
      isAvailable: true,
      isVerified: false,
      rating: 3.8,
      totalTrips: 12
    },
    {
      userId: driverUsers[9].id,
      truckType: TruckType.MINI_TRUCK,
      capacity: 1.0,
      quality: TruckQuality.GOOD,
      license: 'DL-369258147',
      registration: 'BAR-369258',
      documents: ['license.pdf', 'registration.pdf', 'insurance.pdf'],
      location: locations[13].name,
      latitude: locations[13].lat,
      longitude: locations[13].lng,
      isAvailable: true,
      isVerified: true,
      rating: 4.3,
      totalTrips: 38
    },
    // Additional drivers to increase total trucks > 10
    {
      userId: driverUsers[10]?.id,
      truckType: TruckType.PICKUP,
      capacity: 2.0,
      quality: TruckQuality.GOOD,
      license: 'DL-555111222',
      registration: 'DHK-551122',
      documents: ['license.pdf', 'registration.pdf'],
      location: locations[4].name,
      latitude: locations[4].lat,
      longitude: locations[4].lng,
      isAvailable: true,
      isVerified: true,
      rating: 4.1,
      totalTrips: 20
    },
    {
      userId: driverUsers[11]?.id,
      truckType: TruckType.MINI_TRUCK,
      capacity: 1.2,
      quality: TruckQuality.AVERAGE,
      license: 'DL-555333444',
      registration: 'DHK-533444',
      documents: ['license.pdf', 'registration.pdf'],
      location: locations[5].name,
      latitude: locations[5].lat,
      longitude: locations[5].lng,
      isAvailable: false,
      isVerified: true,
      rating: 3.9,
      totalTrips: 18
    },
    {
      userId: driverUsers[12]?.id,
      truckType: TruckType.LORRY,
      capacity: 6.0,
      quality: TruckQuality.GOOD,
      license: 'DL-999666333',
      registration: 'DHK-966633',
      documents: ['license.pdf', 'registration.pdf', 'insurance.pdf'],
      location: locations[6].name,
      latitude: locations[6].lat,
      longitude: locations[6].lng,
      isAvailable: true,
      isVerified: true,
      rating: 4.4,
      totalTrips: 41
    },
    {
      userId: driverUsers[13]?.id,
      truckType: TruckType.TRUCK,
      capacity: 12.0,
      quality: TruckQuality.EXCELLENT,
      license: 'DL-222333444',
      registration: 'DHK-223344',
      documents: ['license.pdf', 'registration.pdf', 'insurance.pdf', 'fitness.pdf'],
      location: locations[7].name,
      latitude: locations[7].lat,
      longitude: locations[7].lng,
      isAvailable: true,
      isVerified: true,
      rating: 4.9,
      totalTrips: 102
    },
    {
      userId: driverUsers[14]?.id,
      truckType: TruckType.PICKUP,
      capacity: 1.5,
      quality: TruckQuality.GOOD,
      license: 'DL-112233445',
      registration: 'DHK-112233',
      documents: ['license.pdf', 'registration.pdf'],
      location: locations[8].name,
      latitude: locations[8].lat,
      longitude: locations[8].lng,
      isAvailable: true,
      isVerified: true,
      rating: 4.0,
      totalTrips: 25
    },
    {
      userId: driverUsers[15]?.id,
      truckType: TruckType.MINI_TRUCK,
      capacity: 0.8,
      quality: TruckQuality.GOOD,
      license: 'DL-667788990',
      registration: 'DHK-778899',
      documents: ['license.pdf', 'registration.pdf'],
      location: locations[9].name,
      latitude: locations[9].lat,
      longitude: locations[9].lng,
      isAvailable: true,
      isVerified: false,
      rating: 3.7,
      totalTrips: 9
    },
    {
      userId: driverUsers[16]?.id,
      truckType: TruckType.LORRY,
      capacity: 7.0,
      quality: TruckQuality.EXCELLENT,
      license: 'DL-445566778',
      registration: 'DHK-556677',
      documents: ['license.pdf', 'registration.pdf', 'insurance.pdf'],
      location: locations[10].name,
      latitude: locations[10].lat,
      longitude: locations[10].lng,
      isAvailable: false,
      isVerified: true,
      rating: 4.6,
      totalTrips: 58
    },
    {
      userId: driverUsers[17]?.id,
      truckType: TruckType.TRUCK,
      capacity: 15.0,
      quality: TruckQuality.EXCELLENT,
      license: 'DL-123987456',
      registration: 'DHK-398745',
      documents: ['license.pdf', 'registration.pdf', 'insurance.pdf', 'fitness.pdf', 'route-permit.pdf'],
      location: locations[11].name,
      latitude: locations[11].lat,
      longitude: locations[11].lng,
      isAvailable: true,
      isVerified: true,
      rating: 4.8,
      totalTrips: 120
    },
    {
      userId: driverUsers[18]?.id,
      truckType: TruckType.PICKUP,
      capacity: 1.0,
      quality: TruckQuality.GOOD,
      license: 'DL-334455667',
      registration: 'DHK-445566',
      documents: ['license.pdf', 'registration.pdf'],
      location: locations[12].name,
      latitude: locations[12].lat,
      longitude: locations[12].lng,
      isAvailable: true,
      isVerified: true,
      rating: 4.2,
      totalTrips: 34
    },
    {
      userId: driverUsers[19]?.id,
      truckType: TruckType.MINI_TRUCK,
      capacity: 1.0,
      quality: TruckQuality.AVERAGE,
      license: 'DL-556677889',
      registration: 'DHK-667788',
      documents: ['license.pdf', 'registration.pdf'],
      location: locations[13].name,
      latitude: locations[13].lat,
      longitude: locations[13].lng,
      isAvailable: true,
      isVerified: true,
      rating: 3.9,
      totalTrips: 16
    }
  ];

  for (const driver of drivers) {
    await prisma.driver.upsert({
      where: { userId: driver.userId },
      update: {
        truckType: driver.truckType,
        capacity: driver.capacity,
        quality: driver.quality,
        license: driver.license,
        registration: driver.registration,
        documents: driver.documents,
        location: driver.location,
        latitude: driver.latitude,
        longitude: driver.longitude,
        isAvailable: driver.isAvailable,
        isVerified: driver.isVerified,
        rating: driver.rating,
        totalTrips: driver.totalTrips
      },
      create: driver
    });
  }
  
  console.log(`✅ Seeded ${drivers.length} drivers`);
} 